server:
  port: 8184

spring:
  jpa:
    show-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified #with binaryTransfer : the data will be transferred from postgres server to jdbc driver in binary form, so it will be transferred faster as this will eliminate the need for conversion by converting a number from their text representation to their binary representation
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always